name: QBCore
version: 2.0
author: Yuvraj Verma
description: Testing
 

variables:
    dbHost: localhost
    dbUsername: root
    dbPassword: ""
    dbName: null

tasks:  
  - action: download_github
    src: https://github.com/HeyYuvraj/QBCore-TxAdmin
    ref: main
    dest: ./tmp/qbus

  - action: move_path
    src: ./tmp/qbus/
    dest: ./
  - action: remove_path
  path: ./tmp/qbus