name: QBCore
version: 2.0
author: Yuvraj Verma
description: Testing
 

variables:
    dbHost: localhost
    dbUsername: root
    dbPassword: ""
    dbName: null

tasks:  
  - action: download_github
    src: https://github.com/HeyYuvraj/QBCore-TxAdmin
    ref: main
    dest: ./tmp/qbus

  - action: connect_database

  - action: query_database
    file: ./tmp/qbus/QBCore-TxAdmin/sql.sql

  - action: move_path
    src: ./tmp/qbus/QBCore-TxAdmin/
    dest: ./

  - action: remove_path
    path: ./tmp