name: QBusFW
author: YuvrajVerma
description: Testing

tasks:
  - action: download_github
    src: https://github.com/HeyYuvraj/QBCore-TxAdmin
    dest: ./temp/

  - action: move_path
    src: ./temp/resources
    dest: ./resources
    overwrite: true

  - action: move_path
    src: ./temp/server.cfg
    dest: ./server.cfg
    overwrite: true

  - action: move_path
    src: ./temp/logo.png
    dest: ./logo.png
    overwrite: true

