author: "Yuvraj Verma"
description: ""Testing"
 

variables:
    dbHost: localhost
    dbUsername: root
    dbPassword: ""
    dbName: null

tasks:  
  # Download Server Files
  - action: download_file
    src: https://github.com/HeyYuvraj/QBCore-TxAdmin/archive/refs/heads/main.zip
    dest: ./tmp/

   - action: unzip
    src: ./tmp/QBCore-TxAdmin-main.zip
    dest: ./tmp
  # Download Connecting and Executing SQL
  - action: connect_database

  - action: query_database
    file: ./tmp/QBCore-TxAdmin-main/sql.sql

  - action: move_path
    src: ./tmp/QBCore-TxAdmin-main/
    dest: ./

  - action: remove_path
    path: ./tmp